language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
install:
    - "pip install -r requirements.txt -r requirements-test.txt"
    - "if [[ ${TRAVIS_PYTHON_VERSION::1} != '3' ]]; then pip install -r requirements-py2.txt; fi"
    - "pip freeze"
script: "nosetests --with-coverage --cover-package=mutornadomon"
after_success: coveralls
